/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.control;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Villarreal
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    private int type=0;
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grd1 = new javax.swing.ButtonGroup();
        txtPlaca = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        rbtnAuto = new javax.swing.JRadioButton();
        rbtnMoto = new javax.swing.JRadioButton();

        grd1.add(rbtnAuto);
        grd1.add(rbtnMoto);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pico & Placa");

        txtPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.setToolTipText("Insert the plate number");
        txtPlaca.setName("txtPlaca"); // NOI18N

        txtHora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setText("00:00");
        txtHora.setToolTipText("Insert the time 24h format");
        txtHora.setName("txtHora"); // NOI18N
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setText("dd-mm-yyyy");
        txtFecha.setToolTipText("Insert the date");
        txtFecha.setName("txtFecha"); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        lblPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPlaca.setText("Plate:");

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFecha.setText("Date:");

        lblHora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHora.setText("Hour:");

        lblTitle.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        lblTitle.setText("Pico & Placa");

        btnCheck.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        rbtnAuto.setText("Automobile");
        rbtnAuto.setToolTipText("Example: AAA1234");
        rbtnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAutoActionPerformed(evt);
            }
        });

        rbtnMoto.setText("Bike");
        rbtnMoto.setToolTipText("Example:AA123A");
        rbtnMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnCheck)
                        .addGap(30, 30, 30)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHora)
                            .addComponent(lblFecha)
                            .addComponent(lblPlaca))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnAuto)
                                    .addComponent(rbtnMoto)))
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblTitle)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlaca)
                                .addGap(38, 38, 38)
                                .addComponent(lblFecha)
                                .addGap(40, 40, 40)
                                .addComponent(lblHora))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(rbtnAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMoto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck)
                    .addComponent(btnExit))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void rbtnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAutoActionPerformed
        // TODO add your handling code here:
        //change the value of type, when its a car it will be 1
        if(rbtnAuto.isSelected()){
            type=1;
        }      
    }//GEN-LAST:event_rbtnAutoActionPerformed

    private void rbtnMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMotoActionPerformed
        // TODO add your handling code here:
        //change the value of type, when its a bike it will be 2
        if(rbtnMoto.isSelected()){
            type=2;
        }
    }//GEN-LAST:event_rbtnMotoActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        //This first while loop evaluates the data typed by the user, and will keep on doing so until all the
        //data is typed correctly
        boolean check = false;
        while(check==false){
            check=true;
            String error= control.totalValidation(txtPlaca.getText().trim(), txtFecha.getText().trim(), txtHora.getText().trim(), type);
            if(!error.equals("")){
                check=false;
                JOptionPane.showMessageDialog(null,error , "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        //Uses the methods from the control class to determine wether the car/bike can be on the road or not and displays the message
        if(control.picoyPlaca(txtPlaca.getText().trim(), type, txtHora.getText().trim())){
            JOptionPane.showMessageDialog(null,"You can be on the road. Drive safely!" , "Result", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"It's "+control.getDay()+"\nYou can't drive between 07:00---09:30 and 16:00---19:30\nYou'll have to wait for Pico & Placa to end!" , "Result", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup grd1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnAuto;
    private javax.swing.JRadioButton rbtnMoto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
